Update to mpich2-1.0.6p1
git-svn-id: https://svn-wrf-var.cgd.ucar.edu/vendor@3351 70815b0f-b814-0410-81f7-dfa10a885da6

diff --git a/mpich2/current/maint/updatefiles b/mpich2/current/maint/updatefiles
--- a/mpich2/current/maint/updatefiles
+++ b/mpich2/current/maint/updatefiles
@@ -30,6 +30,7 @@ fi
 # depend choices are dynamic, static, no
 do_depend=dynamic
 do_geterrmsgs=yes
+do_getparms=no
 do_bindings=yes
 do_f77=yes
 do_f77tof90=yes
@@ -44,7 +45,7 @@ MAKE=${MAKE-make}
 
 # List of steps that we will consider
 # (We do not include depend because the values for depend are not just yes/no)
-AllSteps="geterrmsgs bindings f77 f77tof90 build_configure genstates makefiles smpdversion"
+AllSteps="geterrmsgs bindings f77 f77tof90 build_configure genstates makefiles smpdversion getparms"
 stepsCleared=no
 
 # Options for some steps
@@ -181,9 +182,9 @@ fi
 # Check that you have a working autoconf.  Autoconf 2.57 is not compatible with
 # previous versions of autoconf (!!), even 2.52 (!!!).  
 acVersion=ok
-if test -d .tmp ; then rm -rf .tmp ; fi
-if test -s .tmp ; then rm -f .tmp ; fi
-if test ! -d .tmp ; then
+if [ -d .tmp ] ; then rm -rf .tmp ; fi
+if [ -s .tmp ] ; then rm -f .tmp ; fi
+if [ ! -d .tmp ] ; then
     mkdir .tmp 2>&1 >/dev/null
 fi
 # As of autoconf 2.59, the command line arguments changed (again)
@@ -228,51 +229,42 @@ rm -rf .tmp
 #
 # Create the bindings if necessary 
 if [ $do_bindings = "yes" ] ; then
+    build_f77=no
+    build_f90=no
+    build_cxx=no
     if [ $do_f77 = "yes" ] ; then
         if [ ! -s src/binding/f77/abortf.c ] ; then 
 	    build_f77=yes
-        elif find src/binding/f77 -name 'buildiface' -newer 'src/binding/f77/abortf.c' ; then
+        elif find src/binding/f77 -name 'buildiface' -newer 'src/binding/f77/abortf.c' >/dev/null 2>&1 ; then
 	    build_f77=yes
-        else
-	    build_f77=no
         fi
-    else
-        build_f77=no
+        if [ ! -s src/binding/f90/mpi_base.f90 ] ; then
+ 	    build_f90=yes
+        elif find src/binding/f90 -name 'buildiface' -newer 'src/binding/f90/mpi_base.f90' >/dev/null 2>&1 ; then
+	    build_f90=yes
+        fi
+ 
     fi
 
     if [ $build_f77 = "yes" ] ; then
 	echo "Building Fortran 77 interface"
 	( cd src/binding/f77 && chmod a+x ./buildiface && ./buildiface )
     fi
+    if [ $build_f90 = "yes" ] ; then
+	echo "Building Fortran 90 interface"
+	( cd src/binding/f90 && chmod a+x ./buildiface && ./buildiface )
+	( cd src/binding/f90 && ../f77/buildiface -infile=cf90t.h -deffile=cf90tdefs)
+    fi
 
     if [ ! -s src/binding/cxx/mpicxx.h ] ; then 
 	build_cxx=yes
-    elif find src/binding/cxx -name 'buildiface' -newer 'src/binding/cxx/mpicxx.h' ; then
+    elif find src/binding/cxx -name 'buildiface' -newer 'src/binding/cxx/mpicxx.h' >/dev/null 2>&1 ; then
 	build_cxx=yes
-    else
-	build_cxx=no
     fi
     if [ $build_cxx = "yes" ] ; then
 	echo "Building C++ interface"
-    #    File code still needs work
-    #    if [ ! -d src/mpi/romio ] ; then
-#	    otherarg="-noromio"
-    #    fi
 	( cd src/binding/cxx && chmod a+x ./buildiface &&
 	  ./buildiface -nosep $otherarg )
-    fi
-
-    if [ ! -s src/binding/f90/mpi.f90 ] ; then
-	build_f90=yes
-    elif find src/binding/f90 -name 'buildiface' -newer 'src/binding/f90/mpi.f90' ; then
-	build_f90=yes
-    else
-	build_f90=no
-    fi
-    if [ $build_f90 = "yes" -a -s src/binding/f90/buildiface ] ; then
-	echo "Building F90 interface"
-	( cd src/binding/f90 && chmod a+x ./buildiface && \
-	    ./buildiface $otherarg)
     fi
 fi
 #
@@ -353,7 +345,7 @@ run_configure=no
 # autom4te*.cache file; since this cache is not accurate, we delete it.
 if [ ! -x maint/configure ] ; then
     (cd maint && $autoconf && rm -rf autom4te*.cache )
-elif find maint -name 'configure.in' -newer 'maint/configure' ; then
+elif find maint -name 'configure.in' -newer 'maint/configure' >/dev/null 2>&1 ; then
     # The above relies on the Unix find command
     (cd maint && $autoconf && rm -rf autom4te*.cache)
 fi
@@ -363,14 +355,14 @@ fi
 #
 # The following relies on the Unix find command
 if [ -s maint/simplemake ] ; then
-    if find maint -name 'simplemake.in' -newer 'maint/simplemake' ; then
+    if find maint -name 'simplemake.in' -newer 'maint/simplemake' >/dev/null 2>&1 ; then
         run_configure=yes
     fi
 else
     run_configure=yes
 fi
 if [ -s maint/genstates ] ; then 
-    if find maint -name 'genstates.in' -newer 'maint/genstates' ; then
+    if find maint -name 'genstates.in' -newer 'maint/genstates' >/dev/null 2>&1 ; then
         run_configure=yes
     fi
 else
@@ -401,6 +393,9 @@ if [ -x maint/extractstates -a $do_genstates = "yes" ] ; then
     echo "Creating the enumeration of logging states into src/include/mpiallstates.h"
     maint/extractstates
 fi
+if [ -x maint/extractparms -a $do_getparms = "yes" ] ; then
+    maint/extractparms -outfile=parms.htm
+fi
 # Create and/or update the f90 tests
 if [ -x maint/f77tof90 -a $do_f77tof90 = "yes" ] ; then
     echo "Create or update the Fortran 90 tests derived from the Fortran 77 tests"
@@ -415,10 +410,10 @@ if [ -x maint/f77tof90 -a $do_f77tof90 = "yes" ] ; then
 fi
 
 if [ $made_simplemake != "no" -a $do_makefiles = yes ] ; then
-    # Check that only the first line was changed:
+    # Check that only the first three lines were changed:
     rm -f .t1 .t2
-    sed -e 1d maint/simplemake.in > .t1
-    sed -e 1d maint/simplemake > .t2
+    sed -e 1,3d maint/simplemake.in > .t1
+    sed -e 1,3d maint/simplemake > .t2
     if diff .t1 .t2 >/dev/null 2>&1 ; then
         :
     else
@@ -502,12 +497,19 @@ if [ $do_build_configure = yes ] ; then
 	    if [ -d $confdbSrcDir ] ; then
                 cp -rp $confdbSrcDir confdb
                 # Remove the CVS directories
-		if test -d confdb/CVS ; then
+		if [ -d confdb/CVS ] ; then
                     (cd confdb && find . -name CVS -print | xargs rm -rf)
                 fi
             else
-                echo "Directory `pwd`/confdb is missing and is required for rebuilding configure"
-  	        exit 1
+		# Try to use scp
+                scp -rp shakey.mcs.anl.gov:$confdbSrcDir confdb
+		if [ -d confdb/CVS ] ; then
+		    (cd confdb && find . -name CVS -print | xargs rm -rf)
+                fi
+		if [ ! -d confdb ] ; then    
+                    echo "Directory `pwd`/confdb is missing and is required for rebuilding configure"
+  	            exit 1
+                fi
             fi
         elif [ -d confdb -a -d "$confdbSrcDir" -a ! -d confdb/CVS ] ; then
             # This is a copy; get an up-to-date copy.  We only do 
@@ -515,7 +517,7 @@ if [ $do_build_configure = yes ] ; then
 	    # part of the distributed version and not local.
             cp -rp $confdbSrcDir confdb
             # Remove the CVS directories
-	    if test -d confdb/CVS ; then
+	    if [ -d confdb/CVS ] ; then
                 (cd confdb && find . -name CVS -print | xargs rm -rf)
             fi
         fi
diff --git a/mpich2/current/src/mpid/ch3/channels/shm/setup_channel b/mpich2/current/src/mpid/ch3/channels/shm/setup_channel
--- a/mpich2/current/src/mpid/ch3/channels/shm/setup_channel
+++ b/mpich2/current/src/mpid/ch3/channels/shm/setup_channel
@@ -29,8 +29,9 @@ pathlist=""
 pathlist="$pathlist src/mpid/${device_name}/channels/${channel_name}/include"
 pathlist="$pathlist src/mpid/common/locks"
 for path in $pathlist ; do
-    CPPFLAGS="$CPPFLAGS -I`pwd`/${path}"
-    CPPFLAGS="$CPPFLAGS -I${master_top_srcdir}/${path}"
+    #CPPFLAGS="$CPPFLAGS -I`pwd`/${path}"
+    #CPPFLAGS="$CPPFLAGS -I${master_top_srcdir}/${path}"
+    MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I${master_top_builddir}/${path} -I${master_top_srcdir}/${path}"
 done
 
 devsubsystems="$devsubsystems src/mpid/common/locks"
@@ -53,4 +54,7 @@ file=${dir}/setup
 if test -f $file ; then
     echo sourcing $file
     . $file
+else 
+    echo "Cannot find $file , needed to build process locks"
+    exit 1
 fi
diff --git a/mpich2/current/src/mpid/common/locks/configure b/mpich2/current/src/mpid/common/locks/configure
--- a/mpich2/current/src/mpid/common/locks/configure
+++ b/mpich2/current/src/mpid/common/locks/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="configure.in"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP AR RANLIB MPILIBNAME CC_SHL C_LINK_SHL LIBTOOL ENABLE_SHLIB master_top_srcdir MAKE_DEPEND_C LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAKE VPATH SET_CFLAGS SET_MAKE AR RANLIB CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP MPILIBNAME CC_SHL C_LINK_SHL LIBTOOL ENABLE_SHLIB SHLIB_EXT master_top_srcdir ETAGS ETAGSADD MAKE_DEPEND_C LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -900,7 +900,7 @@ esac
     else
       echo "$as_me: WARNING: no configuration information is in $ac_dir" >&2
     fi
-    cd $ac_popdir
+    cd "$ac_popdir"
   done
 fi
 
@@ -1435,6 +1435,355 @@ echo "$as_me: error: You cannot do a VPATH build if the source directory has bee
     fi
 fi
 rm -f conftest*
+
+
+
+true
+if test "X$MAKE" = "X" ; then
+   for ac_prog in make gnumake nmake pmake smake
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_MAKE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$MAKE"; then
+  ac_cv_prog_MAKE="$MAKE" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_MAKE="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+MAKE=$ac_cv_prog_MAKE
+if test -n "$MAKE"; then
+  echo "$as_me:$LINENO: result: $MAKE" >&5
+echo "${ECHO_T}$MAKE" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$MAKE" && break
+done
+
+fi
+
+
+echo "$as_me:$LINENO: checking whether clock skew breaks make" >&5
+echo $ECHO_N "checking whether clock skew breaks make... $ECHO_C" >&6
+if test "${pac_cv_prog_make_found_clock_skew+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+
+rm -f conftest*
+cat > conftest <<EOF
+ALL:
+	@-echo "success"
+EOF
+$MAKE -f conftest > conftest.out 2>&1
+if grep -i skew conftest >/dev/null 2>&1 ; then
+    pac_cv_prog_make_found_clock_skew=yes
+else
+    pac_cv_prog_make_found_clock_skew=no
+fi
+rm -f conftest*
+
+fi
+echo "$as_me:$LINENO: result: $pac_cv_prog_make_found_clock_skew" >&5
+echo "${ECHO_T}$pac_cv_prog_make_found_clock_skew" >&6
+if test "$pac_cv_prog_make_found_clock_skew" = "yes" ; then
+    { echo "$as_me:$LINENO: WARNING: Clock skew found by make.  The configure and build may fail.
+Consider building in a local instead of NFS filesystem." >&5
+echo "$as_me: WARNING: Clock skew found by make.  The configure and build may fail.
+Consider building in a local instead of NFS filesystem." >&2;}
+fi
+
+
+echo "$as_me:$LINENO: checking whether make supports include" >&5
+echo $ECHO_N "checking whether make supports include... $ECHO_C" >&6
+if test "${pac_cv_prog_make_include+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+
+rm -f conftest
+cat > conftest <<.
+ALL:
+	@echo "success"
+.
+cat > conftest1 <<.
+include conftest
+.
+pac_str=`$MAKE -f conftest1 2>&1`
+rm -f conftest conftest1
+if test "$pac_str" != "success" ; then
+    pac_cv_prog_make_include="no"
+else
+    pac_cv_prog_make_include="yes"
+fi
+
+fi
+echo "$as_me:$LINENO: result: $pac_cv_prog_make_include" >&5
+echo "${ECHO_T}$pac_cv_prog_make_include" >&6
+if test "$pac_cv_prog_make_include" = "no" ; then
+    :
+else
+    :
+fi
+
+
+echo "$as_me:$LINENO: checking whether make allows comments in actions" >&5
+echo $ECHO_N "checking whether make allows comments in actions... $ECHO_C" >&6
+if test "${pac_cv_prog_make_allows_comments+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+
+rm -f conftest
+cat > conftest <<.
+SHELL=/bin/sh
+ALL:
+	@# This is a valid comment!
+	@echo "success"
+.
+pac_str=`$MAKE -f conftest 2>&1`
+rm -f conftest
+if test "$pac_str" != "success" ; then
+    pac_cv_prog_make_allows_comments="no"
+else
+    pac_cv_prog_make_allows_comments="yes"
+fi
+
+fi
+echo "$as_me:$LINENO: result: $pac_cv_prog_make_allows_comments" >&5
+echo "${ECHO_T}$pac_cv_prog_make_allows_comments" >&6
+if test "$pac_cv_prog_make_allows_comments" = "no" ; then
+    { echo "$as_me:$LINENO: WARNING: Your make does not allow comments in target code.
+Using this make may cause problems when building programs.
+You should consider using gnumake instead." >&5
+echo "$as_me: WARNING: Your make does not allow comments in target code.
+Using this make may cause problems when building programs.
+You should consider using gnumake instead." >&2;}
+
+fi
+
+
+
+echo "$as_me:$LINENO: checking for virtual path format" >&5
+echo $ECHO_N "checking for virtual path format... $ECHO_C" >&6
+if test "${pac_cv_prog_make_vpath+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+
+rm -rf conftest*
+mkdir conftestdir
+cat >conftestdir/a.c <<EOF
+A sample file
+EOF
+cat > conftest <<EOF
+all: a.o
+VPATH=.:conftestdir
+.c.o:
+	@echo \$<
+EOF
+ac_out=`$MAKE -f conftest 2>&1 | grep 'conftestdir/a.c'`
+if test -n "$ac_out" ; then
+    pac_cv_prog_make_vpath="VPATH"
+else
+    rm -f conftest
+    cat > conftest <<EOF
+all: a.o
+.PATH: . conftestdir
+.c.o:
+	@echo \$<
+EOF
+    ac_out=`$MAKE -f conftest 2>&1 | grep 'conftestdir/a.c'`
+    if test -n "$ac_out" ; then
+        pac_cv_prog_make_vpath=".PATH"
+    else
+	pac_cv_prog_make_vpath="neither VPATH nor .PATH works"
+    fi
+fi
+rm -rf conftest*
+
+fi
+echo "$as_me:$LINENO: result: $pac_cv_prog_make_vpath" >&5
+echo "${ECHO_T}$pac_cv_prog_make_vpath" >&6
+if test "$pac_cv_prog_make_vpath" = "VPATH" ; then
+    VPATH='VPATH=.:${srcdir}'
+elif test "$pac_cv_prog_make_vpath" = ".PATH" ; then
+    VPATH='.PATH: . ${srcdir}'
+fi
+
+
+
+echo "$as_me:$LINENO: checking whether make sets CFLAGS" >&5
+echo $ECHO_N "checking whether make sets CFLAGS... $ECHO_C" >&6
+if test "${pac_cv_prog_make_set_cflags+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+
+rm -f conftest
+cat > conftest <<EOF
+SHELL=/bin/sh
+ALL:
+	@echo X\${CFLAGS}X
+EOF
+pac_str=`$MAKE -f conftest 2>&1`
+rm -f conftest
+if test "$pac_str" = "XX" ; then
+    pac_cv_prog_make_set_cflags="no"
+else
+    pac_cv_prog_make_set_cflags="yes"
+fi
+
+fi
+echo "$as_me:$LINENO: result: $pac_cv_prog_make_set_cflags" >&5
+echo "${ECHO_T}$pac_cv_prog_make_set_cflags" >&6
+if test "$pac_cv_prog_make_set_cflags" = "no" ; then
+    :
+else
+    SET_CFLAGS='CFLAGS='
+fi
+
+if test "$pac_cv_prog_make_echos_dir" = "no" ; then
+    echo "$as_me:$LINENO: checking whether ${MAKE-make} sets \$(MAKE)" >&5
+echo $ECHO_N "checking whether ${MAKE-make} sets \$(MAKE)... $ECHO_C" >&6
+set dummy ${MAKE-make}; ac_make=`echo "$2" | sed 'y,:./+-,___p_,'`
+if eval "test \"\${ac_cv_prog_make_${ac_make}_set+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.make <<\_ACEOF
+all:
+	@echo 'ac_maketemp="$(MAKE)"'
+_ACEOF
+# GNU make sometimes prints "make[1]: Entering...", which would confuse us.
+eval `${MAKE-make} -f conftest.make 2>/dev/null | grep temp=`
+if test -n "$ac_maketemp"; then
+  eval ac_cv_prog_make_${ac_make}_set=yes
+else
+  eval ac_cv_prog_make_${ac_make}_set=no
+fi
+rm -f conftest.make
+fi
+if eval "test \"`echo '$ac_cv_prog_make_'${ac_make}_set`\" = yes"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  SET_MAKE=
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  SET_MAKE="MAKE=${MAKE-make}"
+fi
+
+else
+    SET_MAKE="MAKE=${MAKE-make}"
+fi
+
+for ac_prog in ar
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_AR+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$AR"; then
+  ac_cv_prog_AR="$AR" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_AR="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+AR=$ac_cv_prog_AR
+if test -n "$AR"; then
+  echo "$as_me:$LINENO: result: $AR" >&5
+echo "${ECHO_T}$AR" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$AR" && break
+done
+
+if test -z "$AR" ; then
+    { { echo "$as_me:$LINENO: error: The program ar is required for building MPICH2.  Make sure that your path includes ar" >&5
+echo "$as_me: error: The program ar is required for building MPICH2.  Make sure that your path includes ar" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+# Note that we set RANLIB to true if we don't find it (some systems neither
+# need it nor provide it)
+for ac_prog in ranlib
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_RANLIB+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$RANLIB"; then
+  ac_cv_prog_RANLIB="$RANLIB" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_RANLIB="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+RANLIB=$ac_cv_prog_RANLIB
+if test -n "$RANLIB"; then
+  echo "$as_me:$LINENO: result: $RANLIB" >&5
+echo "${ECHO_T}$RANLIB" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$RANLIB" && break
+done
+test -n "$RANLIB" || RANLIB="true"
 
 
 ac_ext=c
@@ -2005,8 +2354,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2064,8 +2412,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2181,8 +2528,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2236,8 +2582,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2282,8 +2627,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2327,8 +2671,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2441,8 +2784,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2544,8 +2886,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2647,8 +2988,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2966,7 +3306,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 2969 "configure"
+#line 3309 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -3016,10 +3356,12 @@ _ACEOF
     # always reach all of the necessary files (I saw failures in ch3_progress.c
     # where the inline file was not in the Makefile) and (a) adds the inline
     # where it should not be, such as in mpicc.
-    { { echo "$as_me:$LINENO: error: Use of inline process locks is not supported.  Please volunteer to fix this code" >&5
-echo "$as_me: error: Use of inline process locks is not supported.  Please volunteer to fix this code" >&2;}
-   { (exit 1); exit 1; }; }
+    CFLAGS="$CFLAGS $LOCKCFLAGS"
 fi
+
+# Add the MPICH2 include flags to CPPFLAGS.
+CPPFLAGS="$CPPFLAGS $MPICH2_INCLUDE_FLAGS"
+
 
 
 
@@ -3040,6 +3382,10 @@ echo "$as_me: WARNING: libtool selected for shared library support but LIBTOOL i
 	fi
 
 
+
+
+export ETAGS
+export ETAGSADD
 
 
           ac_config_files="$ac_config_files Makefile"
@@ -3653,6 +3999,12 @@ s,@ECHO_C@,$ECHO_C,;t t
 s,@ECHO_N@,$ECHO_N,;t t
 s,@ECHO_T@,$ECHO_T,;t t
 s,@LIBS@,$LIBS,;t t
+s,@MAKE@,$MAKE,;t t
+s,@VPATH@,$VPATH,;t t
+s,@SET_CFLAGS@,$SET_CFLAGS,;t t
+s,@SET_MAKE@,$SET_MAKE,;t t
+s,@AR@,$AR,;t t
+s,@RANLIB@,$RANLIB,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
@@ -3661,14 +4013,15 @@ s,@ac_ct_CC@,$ac_ct_CC,;t t
 s,@EXEEXT@,$EXEEXT,;t t
 s,@OBJEXT@,$OBJEXT,;t t
 s,@CPP@,$CPP,;t t
-s,@AR@,$AR,;t t
-s,@RANLIB@,$RANLIB,;t t
 s,@MPILIBNAME@,$MPILIBNAME,;t t
 s,@CC_SHL@,$CC_SHL,;t t
 s,@C_LINK_SHL@,$C_LINK_SHL,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
 s,@ENABLE_SHLIB@,$ENABLE_SHLIB,;t t
+s,@SHLIB_EXT@,$SHLIB_EXT,;t t
 s,@master_top_srcdir@,$master_top_srcdir,;t t
+s,@ETAGS@,$ETAGS,;t t
+s,@ETAGSADD@,$ETAGSADD,;t t
 s,@MAKE_DEPEND_C@,$MAKE_DEPEND_C,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
@@ -3834,11 +4187,6 @@ esac
 
 
 
-  if test x"$ac_file" != x-; then
-    { echo "$as_me:$LINENO: creating $ac_file" >&5
-echo "$as_me: creating $ac_file" >&6;}
-    rm -f "$ac_file"
-  fi
   # Let's still pretend it is `configure' which instantiates (i.e., don't
   # use $as_me), people would be surprised to read:
   #    /* config.h.  Generated by config.status.  */
@@ -3877,6 +4225,12 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
 	 fi;;
       esac
     done` || { (exit 1); exit 1; }
+
+  if test x"$ac_file" != x-; then
+    { echo "$as_me:$LINENO: creating $ac_file" >&5
+echo "$as_me: creating $ac_file" >&6;}
+    rm -f "$ac_file"
+  fi
 _ACEOF
 cat >>$CONFIG_STATUS <<_ACEOF
   sed "$ac_vpsub
diff --git a/mpich2/current/src/mpid/common/sock/configure b/mpich2/current/src/mpid/common/sock/configure
--- a/mpich2/current/src/mpid/common/sock/configure
+++ b/mpich2/current/src/mpid/common/sock/configure
@@ -273,7 +273,7 @@ PACKAGE_BUGREPORT=
 
 ac_unique_file="configure.in"
 ac_subdirs_all="$ac_subdirs_all ${sock_name}"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS sock_name MAKE VPATH SET_CFLAGS SET_MAKE AR RANLIB MPILIBNAME CC CFLAGS CPPFLAGS CC_SHL C_LINK_SHL LIBTOOL ENABLE_SHLIB master_top_srcdir master_top_builddir MAKE_DEPEND_C ETAGS ETAGSADD subdirs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS sock_name MAKE VPATH SET_CFLAGS SET_MAKE AR RANLIB MPILIBNAME CC CFLAGS CPPFLAGS CC_SHL C_LINK_SHL LIBTOOL ENABLE_SHLIB SHLIB_EXT master_top_srcdir master_top_builddir MAKE_DEPEND_C ETAGS ETAGSADD subdirs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -869,7 +869,7 @@ esac
     else
       echo "$as_me: WARNING: no configuration information is in $ac_dir" >&2
     fi
-    cd $ac_popdir
+    cd "$ac_popdir"
   done
 fi
 
@@ -1678,6 +1678,95 @@ else
     SET_MAKE="MAKE=${MAKE-make}"
 fi
 
+for ac_prog in ar
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_AR+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$AR"; then
+  ac_cv_prog_AR="$AR" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_AR="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+AR=$ac_cv_prog_AR
+if test -n "$AR"; then
+  echo "$as_me:$LINENO: result: $AR" >&5
+echo "${ECHO_T}$AR" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$AR" && break
+done
+
+if test -z "$AR" ; then
+    { { echo "$as_me:$LINENO: error: The program ar is required for building MPICH2.  Make sure that your path includes ar" >&5
+echo "$as_me: error: The program ar is required for building MPICH2.  Make sure that your path includes ar" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+# Note that we set RANLIB to true if we don't find it (some systems neither
+# need it nor provide it)
+for ac_prog in ranlib
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_RANLIB+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$RANLIB"; then
+  ac_cv_prog_RANLIB="$RANLIB" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_RANLIB="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+RANLIB=$ac_cv_prog_RANLIB
+if test -n "$RANLIB"; then
+  echo "$as_me:$LINENO: result: $RANLIB" >&5
+echo "${ECHO_T}$RANLIB" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$RANLIB" && break
+done
+test -n "$RANLIB" || RANLIB="true"
+
+
 
 
 
@@ -1697,6 +1786,9 @@ echo "$as_me: WARNING: libtool selected for shared library support but LIBTOOL i
             fi
 	fi
 
+if test -z "$ENABLE_SHLIB" -o "$ENABLE_SHLIB" = "no" ; then
+    ENABLE_SHLIB=none
+fi
 
 # Master_top_builddir is imported from the top; use it for the "top"
 # (used for things like libtool)
@@ -1718,10 +1810,18 @@ export ETAGSADD
 
 
 
+export RANLIB
+export AR
+# FIXME: autoconf doesn't like variable names in the config_subdirs call.
 
 
 subdirs="$subdirs ${sock_name}"
 
+
+# Add the MPICH2 include flags to CPPFLAGS.  See the discussion above about
+# which include flags should start in MPICH2_INCLUDE_FLAGS and which in
+# CPPFLAGS
+CPPFLAGS="$CPPFLAGS $MPICH2_INCLUDE_FLAGS"
 
                     ac_config_files="$ac_config_files Makefile localdefs"
 cat >confcache <<\_ACEOF
@@ -2350,6 +2450,7 @@ s,@CC_SHL@,$CC_SHL,;t t
 s,@C_LINK_SHL@,$C_LINK_SHL,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
 s,@ENABLE_SHLIB@,$ENABLE_SHLIB,;t t
+s,@SHLIB_EXT@,$SHLIB_EXT,;t t
 s,@master_top_srcdir@,$master_top_srcdir,;t t
 s,@master_top_builddir@,$master_top_builddir,;t t
 s,@MAKE_DEPEND_C@,$MAKE_DEPEND_C,;t t
@@ -2520,11 +2621,6 @@ esac
 
 
 
-  if test x"$ac_file" != x-; then
-    { echo "$as_me:$LINENO: creating $ac_file" >&5
-echo "$as_me: creating $ac_file" >&6;}
-    rm -f "$ac_file"
-  fi
   # Let's still pretend it is `configure' which instantiates (i.e., don't
   # use $as_me), people would be surprised to read:
   #    /* config.h.  Generated by config.status.  */
@@ -2563,6 +2659,12 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
 	 fi;;
       esac
     done` || { (exit 1); exit 1; }
+
+  if test x"$ac_file" != x-; then
+    { echo "$as_me:$LINENO: creating $ac_file" >&5
+echo "$as_me: creating $ac_file" >&6;}
+    rm -f "$ac_file"
+  fi
 _ACEOF
 cat >>$CONFIG_STATUS <<_ACEOF
   sed "$ac_vpsub
@@ -3017,7 +3119,7 @@ echo "$as_me: error: $ac_sub_configure failed for $ac_dir" >&2;}
    { (exit 1); exit 1; }; }
     fi
 
-    cd $ac_popdir
+    cd "$ac_popdir"
   done
 fi
 
diff --git a/mpich2/current/src/mpid/common/sock/poll/configure b/mpich2/current/src/mpid/common/sock/poll/configure
--- a/mpich2/current/src/mpid/common/sock/poll/configure
+++ b/mpich2/current/src/mpid/common/sock/poll/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="configure.in"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAKE VPATH SET_CFLAGS SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP TCP_LIBS AR RANLIB MPILIBNAME CC_SHL C_LINK_SHL LIBTOOL ENABLE_SHLIB master_top_srcdir master_top_builddir MAKE_DEPEND_C ETAGS ETAGSADD LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAKE VPATH SET_CFLAGS SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP TCP_LIBS AR RANLIB MPILIBNAME CC_SHL C_LINK_SHL LIBTOOL ENABLE_SHLIB SHLIB_EXT master_top_srcdir master_top_builddir MAKE_DEPEND_C ETAGS ETAGSADD LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -906,7 +906,7 @@ esac
     else
       echo "$as_me: WARNING: no configuration information is in $ac_dir" >&2
     fi
-    cd $ac_popdir
+    cd "$ac_popdir"
   done
 fi
 
@@ -2301,8 +2301,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2360,8 +2359,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2477,8 +2475,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2532,8 +2529,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2578,8 +2574,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2623,8 +2618,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2693,8 +2687,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2802,8 +2795,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3156,7 +3148,7 @@ fi
 # If cpp failed, see if the compiler accepts the header.
 if test "$pac_found_header" != "yes" ; then
     cat >conftest.c<<EOF
-#line 3159 "configure"
+#line 3151 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 int conftest() {return 0;}
@@ -3232,8 +3224,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3302,8 +3293,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3363,8 +3353,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3468,8 +3457,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3534,8 +3522,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3609,8 +3596,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3664,8 +3650,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3735,8 +3720,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3790,8 +3774,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3855,8 +3838,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3921,8 +3903,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3965,6 +3946,7 @@ fi
 
 
 
+
 	if test "$ENABLE_SHLIB" = "libtool" ; then
 	    if test -z "$LIBTOOL" ; then
 		{ echo "$as_me:$LINENO: WARNING: libtool selected for shared library support but LIBTOOL is not defined" >&5
@@ -3972,6 +3954,9 @@ echo "$as_me: WARNING: libtool selected for shared library support but LIBTOOL i
             fi
 	fi
 
+if test -z "$ENABLE_SHLIB" -o "$ENABLE_SHLIB" = "no" ; then
+    ENABLE_SHLIB=none
+fi
 
 
 
@@ -4031,6 +4016,14 @@ if test -n "$CONF_BASE_CACHEFILE" -a -s "$CONF_BASE_CACHEFILE" ; then
 	mv $CONF_BASE_CACHEFILE.new $CONF_BASE_CACHEFILE
     fi
 fi
+
+
+# Add the MPICH2 include flags to CPPFLAGS.  See the discussion above about
+# which include flags should start in MPICH2_INCLUDE_FLAGS and which in
+# CPPFLAGS
+CPPFLAGS="$CPPFLAGS $MPICH2_INCLUDE_FLAGS"
+
+          ac_config_commands="$ac_config_commands default-1"
 
 
                     ac_config_files="$ac_config_files Makefile localdefs"
@@ -4451,6 +4444,9 @@ $config_files
 Configuration headers:
 $config_headers
 
+Configuration commands:
+$config_commands
+
 Report bugs to <bug-autoconf@gnu.org>."
 _ACEOF
 
@@ -4549,7 +4545,14 @@ fi
 
 _ACEOF
 
+cat >>$CONFIG_STATUS <<_ACEOF
+#
+# INIT-COMMANDS section.
+#
 
+
+
+_ACEOF
 
 
 
@@ -4560,6 +4563,7 @@ do
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "localdefs" ) CONFIG_FILES="$CONFIG_FILES localdefs" ;;
+  "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "mpidu_socki_conf.h" ) CONFIG_HEADERS="$CONFIG_HEADERS mpidu_socki_conf.h" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
@@ -4574,6 +4578,7 @@ done
 if $ac_need_defaults; then
   test "${CONFIG_FILES+set}" = set || CONFIG_FILES=$config_files
   test "${CONFIG_HEADERS+set}" = set || CONFIG_HEADERS=$config_headers
+  test "${CONFIG_COMMANDS+set}" = set || CONFIG_COMMANDS=$config_commands
 fi
 
 # Have a temporary directory for convenience.  Make it in the build tree
@@ -4665,6 +4670,7 @@ s,@CC_SHL@,$CC_SHL,;t t
 s,@C_LINK_SHL@,$C_LINK_SHL,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
 s,@ENABLE_SHLIB@,$ENABLE_SHLIB,;t t
+s,@SHLIB_EXT@,$SHLIB_EXT,;t t
 s,@master_top_srcdir@,$master_top_srcdir,;t t
 s,@master_top_builddir@,$master_top_builddir,;t t
 s,@MAKE_DEPEND_C@,$MAKE_DEPEND_C,;t t
@@ -4834,11 +4840,6 @@ esac
 
 
 
-  if test x"$ac_file" != x-; then
-    { echo "$as_me:$LINENO: creating $ac_file" >&5
-echo "$as_me: creating $ac_file" >&6;}
-    rm -f "$ac_file"
-  fi
   # Let's still pretend it is `configure' which instantiates (i.e., don't
   # use $as_me), people would be surprised to read:
   #    /* config.h.  Generated by config.status.  */
@@ -4877,6 +4878,12 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
 	 fi;;
       esac
     done` || { (exit 1); exit 1; }
+
+  if test x"$ac_file" != x-; then
+    { echo "$as_me:$LINENO: creating $ac_file" >&5
+echo "$as_me: creating $ac_file" >&6;}
+    rm -f "$ac_file"
+  fi
 _ACEOF
 cat >>$CONFIG_STATUS <<_ACEOF
   sed "$ac_vpsub
@@ -5126,6 +5133,129 @@ echo "$as_me: error: cannot create directory \"$ac_dir\"" >&2;}
     cat $tmp/config.h
     rm -f $tmp/config.h
   fi
+done
+_ACEOF
+cat >>$CONFIG_STATUS <<\_ACEOF
+
+#
+# CONFIG_COMMANDS section.
+#
+for ac_file in : $CONFIG_COMMANDS; do test "x$ac_file" = x: && continue
+  ac_dest=`echo "$ac_file" | sed 's,:.*,,'`
+  ac_source=`echo "$ac_file" | sed 's,[^:]*:,,'`
+  ac_dir=`(dirname "$ac_dest") 2>/dev/null ||
+$as_expr X"$ac_dest" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
+	 X"$ac_dest" : 'X\(//\)[^/]' \| \
+	 X"$ac_dest" : 'X\(//\)$' \| \
+	 X"$ac_dest" : 'X\(/\)' \| \
+	 .     : '\(.\)' 2>/dev/null ||
+echo X"$ac_dest" |
+    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{ s//\1/; q; }
+  	  /^X\(\/\/\)[^/].*/{ s//\1/; q; }
+  	  /^X\(\/\/\)$/{ s//\1/; q; }
+  	  /^X\(\/\).*/{ s//\1/; q; }
+  	  s/.*/./; q'`
+  { if $as_mkdir_p; then
+    mkdir -p "$ac_dir"
+  else
+    as_dir="$ac_dir"
+    as_dirs=
+    while test ! -d "$as_dir"; do
+      as_dirs="$as_dir $as_dirs"
+      as_dir=`(dirname "$as_dir") 2>/dev/null ||
+$as_expr X"$as_dir" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
+	 X"$as_dir" : 'X\(//\)[^/]' \| \
+	 X"$as_dir" : 'X\(//\)$' \| \
+	 X"$as_dir" : 'X\(/\)' \| \
+	 .     : '\(.\)' 2>/dev/null ||
+echo X"$as_dir" |
+    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{ s//\1/; q; }
+  	  /^X\(\/\/\)[^/].*/{ s//\1/; q; }
+  	  /^X\(\/\/\)$/{ s//\1/; q; }
+  	  /^X\(\/\).*/{ s//\1/; q; }
+  	  s/.*/./; q'`
+    done
+    test ! -n "$as_dirs" || mkdir $as_dirs
+  fi || { { echo "$as_me:$LINENO: error: cannot create directory \"$ac_dir\"" >&5
+echo "$as_me: error: cannot create directory \"$ac_dir\"" >&2;}
+   { (exit 1); exit 1; }; }; }
+
+  ac_builddir=.
+
+if test "$ac_dir" != .; then
+  ac_dir_suffix=/`echo "$ac_dir" | sed 's,^\.[\\/],,'`
+  # A "../" for each directory in $ac_dir_suffix.
+  ac_top_builddir=`echo "$ac_dir_suffix" | sed 's,/[^\\/]*,../,g'`
+else
+  ac_dir_suffix= ac_top_builddir=
+fi
+
+case $srcdir in
+  .)  # No --srcdir option.  We are building in place.
+    ac_srcdir=.
+    if test -z "$ac_top_builddir"; then
+       ac_top_srcdir=.
+    else
+       ac_top_srcdir=`echo $ac_top_builddir | sed 's,/$,,'`
+    fi ;;
+  [\\/]* | ?:[\\/]* )  # Absolute path.
+    ac_srcdir=$srcdir$ac_dir_suffix;
+    ac_top_srcdir=$srcdir ;;
+  *) # Relative path.
+    ac_srcdir=$ac_top_builddir$srcdir$ac_dir_suffix
+    ac_top_srcdir=$ac_top_builddir$srcdir ;;
+esac
+
+# Do not use `cd foo && pwd` to compute absolute paths, because
+# the directories may not exist.
+case `pwd` in
+.) ac_abs_builddir="$ac_dir";;
+*)
+  case "$ac_dir" in
+  .) ac_abs_builddir=`pwd`;;
+  [\\/]* | ?:[\\/]* ) ac_abs_builddir="$ac_dir";;
+  *) ac_abs_builddir=`pwd`/"$ac_dir";;
+  esac;;
+esac
+case $ac_abs_builddir in
+.) ac_abs_top_builddir=${ac_top_builddir}.;;
+*)
+  case ${ac_top_builddir}. in
+  .) ac_abs_top_builddir=$ac_abs_builddir;;
+  [\\/]* | ?:[\\/]* ) ac_abs_top_builddir=${ac_top_builddir}.;;
+  *) ac_abs_top_builddir=$ac_abs_builddir/${ac_top_builddir}.;;
+  esac;;
+esac
+case $ac_abs_builddir in
+.) ac_abs_srcdir=$ac_srcdir;;
+*)
+  case $ac_srcdir in
+  .) ac_abs_srcdir=$ac_abs_builddir;;
+  [\\/]* | ?:[\\/]* ) ac_abs_srcdir=$ac_srcdir;;
+  *) ac_abs_srcdir=$ac_abs_builddir/$ac_srcdir;;
+  esac;;
+esac
+case $ac_abs_builddir in
+.) ac_abs_top_srcdir=$ac_top_srcdir;;
+*)
+  case $ac_top_srcdir in
+  .) ac_abs_top_srcdir=$ac_abs_builddir;;
+  [\\/]* | ?:[\\/]* ) ac_abs_top_srcdir=$ac_top_srcdir;;
+  *) ac_abs_top_srcdir=$ac_abs_builddir/$ac_top_srcdir;;
+  esac;;
+esac
+
+
+  { echo "$as_me:$LINENO: executing $ac_dest commands" >&5
+echo "$as_me: executing $ac_dest commands" >&6;}
+  case $ac_dest in
+    default-1 ) if grep 'dependencies:' Makefile >/dev/null 2>&1 ; then
+    if test ! -s .deps/alldeps ; then
+    echo "Updating dependency directories .deps"
+    grep MAKE_DEPEND_C Makefile >/dev/null 2>&1 && \
+       ( test -d .deps || mkdir .deps) && touch .deps/alldeps
+fi; fi ;;
+  esac
 done
 _ACEOF
 
diff --git a/mpich2/current/src/pm/mpd/configure b/mpich2/current/src/pm/mpd/configure
--- a/mpich2/current/src/pm/mpd/configure
+++ b/mpich2/current/src/pm/mpd/configure
@@ -949,7 +949,7 @@ esac
     else
       echo "$as_me: WARNING: no configuration information is in $ac_dir" >&2
     fi
-    cd $ac_popdir
+    cd "$ac_popdir"
   done
 fi
 
@@ -1897,8 +1897,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -1956,8 +1955,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2073,8 +2071,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2128,8 +2125,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2174,8 +2170,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2219,8 +2214,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2738,18 +2732,6 @@ echo "${ECHO_T}no" >&6
             continue
         fi
 
-        if test "$enable_totalview" = "yes" ; then
-            echo "$as_me:$LINENO: checking that $pypgm has development tools for totalview" >&5
-echo $ECHO_N "checking that $pypgm has development tools for totalview... $ECHO_C" >&6
-            if test -f /usr/lib/$pypgm/config/Makefile ; then
-                echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-            else
-                echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-                continue
-            fi
-        fi
 
         PYTHON="$pypgm"
         break
@@ -2826,8 +2808,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2881,8 +2862,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3199,8 +3179,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3371,8 +3350,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3442,8 +3420,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3515,8 +3492,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3703,8 +3679,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   cat conftest.err >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -3736,6 +3711,173 @@ _ACEOF
 fi
 done
 
+
+
+for ac_func in snprintf
+do
+as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_func" >&5
+echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
+if eval "test \"\${$as_ac_var+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define $ac_func to an innocuous variant, in case <limits.h> declares $ac_func.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define $ac_func innocuous_$ac_func
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef $ac_func
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+{
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $ac_func ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+choke me
+#else
+char (*f) () = $ac_func;
+#endif
+#ifdef __cplusplus
+}
+#endif
+
+int
+main ()
+{
+return f != $ac_func;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_var=no"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+done
+
+if test "$ac_cv_func_snprintf" = "yes" ; then
+
+echo "$as_me:$LINENO: checking whether snprintf needs a declaration" >&5
+echo $ECHO_N "checking whether snprintf needs a declaration... $ECHO_C" >&6
+if test "${pac_cv_func_decl_snprintf+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <stdio.h>
+int
+main ()
+{
+int a=snprintf(1.0,27,1.0,"foo");
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  pac_cv_func_decl_snprintf=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+pac_cv_func_decl_snprintf=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $pac_cv_func_decl_snprintf" >&5
+echo "${ECHO_T}$pac_cv_func_decl_snprintf" >&6
+if test "$pac_cv_func_decl_snprintf" = "yes" ; then
+
+cat >>confdefs.h <<_ACEOF
+#define NEEDS_SNPRINTF_DECL 1
+_ACEOF
+
+
+fi
+
+fi
 
 # Starting output
 MPD_HOME=`pwd`
@@ -4549,11 +4691,6 @@ esac
   *) ac_INSTALL=$ac_top_builddir$INSTALL ;;
   esac
 
-  if test x"$ac_file" != x-; then
-    { echo "$as_me:$LINENO: creating $ac_file" >&5
-echo "$as_me: creating $ac_file" >&6;}
-    rm -f "$ac_file"
-  fi
   # Let's still pretend it is `configure' which instantiates (i.e., don't
   # use $as_me), people would be surprised to read:
   #    /* config.h.  Generated by config.status.  */
@@ -4592,6 +4729,12 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
 	 fi;;
       esac
     done` || { (exit 1); exit 1; }
+
+  if test x"$ac_file" != x-; then
+    { echo "$as_me:$LINENO: creating $ac_file" >&5
+echo "$as_me: creating $ac_file" >&6;}
+    rm -f "$ac_file"
+  fi
 _ACEOF
 cat >>$CONFIG_STATUS <<_ACEOF
   sed "$ac_vpsub
diff --git a/mpich2/current/src/util/createshlib.in b/mpich2/current/src/util/createshlib.in
--- a/mpich2/current/src/util/createshlib.in
+++ b/mpich2/current/src/util/createshlib.in
@@ -1,4 +1,5 @@
 #! /bin/sh
+#set -x
 # -*- Mode: shell-script; -*-
 #
 # This is a simplified tool for creating and installing shared libraries
@@ -22,7 +23,7 @@
 #
 # Set the characteristics of the shared library support, determined 
 # by configure
-CC="@CC@"
+CC="@CC@ @CFLAGS@"
 C_LINK_SHL="@C_LINK_SHL@"
 SHLIB_EXT="@SHLIB_EXT@"
 INSTALL="@INSTALL@"
@@ -60,6 +61,9 @@ for arg in "$@" ; do
 	   # to export, one per line.
 	   exportDefs=$arg
 	   ;;
+           -version-info)
+           ABIVersion=$arg
+           ;;
 	   *)
 	   # Ignoring things like version info for now
 	   ;;
@@ -74,18 +78,19 @@ for arg in "$@" ; do
 
    case $arg in 
        --mode=*) mode=$option ;;
-       -o|-rpath|-version-info|-export) # next arg is value for this option
+       -o|-rpath|-export|-version-info) # next arg is value for this option
        nextarg=$arg
        ;;
        -echo) set -x ;;
        -dryrun) Show=echo ;;
-       -l*|-L*)
-       dependentLibs="$dependentLibs $arg"
-       ;;
        # -cc and -clink allow us to override the commands used to 
        # build the shared library
        -cc=*) CC_SHL=$option ;;
        -clink=*) C_LINK_SHL=$option ;;
+       -libtype=*) libtype=$option ;;
+       -l*|-L*)
+       dependentLibs="$dependentLibs $arg"
+       ;;
        *)
        # The remaining arguments are used for install
        if [ -z "$srclibname" ] ; then
@@ -106,11 +111,110 @@ fi
 
 # Peel the srclibname into the srclibdir, srclibbase, srclibext
 srclibext=`echo $srclibname | sed -e 's/.*\.//'`
-srclibdir=`echo $srclibname | sed 's/\(.*\)\/.*/\1/'`
+srclibdir=`echo $srclibname | sed -e 's/\(.*\)\/.*/\1/'`
 if [ "$srclibdir" = "$srclibname" ] ; then
     srclibdir=.
 fi
 srclibbase=`basename $srclibname .$srclibext`
+
+if [ -z "$destdir" -a -n "$destlibname" ] ; then
+    # This works because of the eager nature of the RE match (everything
+    # up to the last / is matched in the first expression)
+    destdir=`echo $destlibname | sed -e 's/\(.*\)\/.*/\1/'`
+    destBaseName=`echo $destlibname | sed -e 's/.*\/\(.*\)/\1/'`
+fi
+
+# The convention for "soname" is the following:
+# soname contains the following
+#    name of library
+#    shared library suffix (typically .so or .dylib)
+#    a version number
+# The version number is not the same as the version number of the
+# of the library.  Instead, it is the version number of the ABI for the
+# library.  That allows applications to use any version of the library that
+# has the same ABI.
+# In cases where there are major changes in behavior but not in the ABI,
+# it makes sense to note those as a minor version number.  Thus, we prefer
+# to have a ABIversion number with which to create the soname
+#
+# In addition, it is common to have a primary name that includes some
+# (or all) version information and then one or more soft links to a 
+# "generic" name that does not include version information.  For example,
+# under most Unix systems, there may be a 
+#
+#   libfoo.so.1.2.2
+#   libfoo.so.1
+#   libfoo.so
+# with only the "libfoo.so.1.2.2" being a file; the others are links.
+# Under OSX, the name scheme is a little different, 
+#   libfoo.1.2.3.dylib
+#   libfoo.1.dylib
+#   libfoo.dylib
+# where again the "libfoo.1.2.2.dylib" is the file and the others are links.
+# These links need to be established during the installation phase.
+#
+# To handle this, we fill in three variables:
+#   
+#   realName - name of the file (with no directory)
+#   soName   - name of the shared object (often realName)
+#   altNames - alternate names when installed
+#
+# There is also 
+#   minorVersionArg - argument used to indicate minor version number to 
+#              program that creates shared library.  Used only (so far)
+#              with osx
+#
+# For now, there are only two versions of this.  The osx one and everyone 
+# else.  Most Unix systems will use the default.
+#
+# Note that the names depend on the ABIVersion, so we extract the information
+# on the version numbers from ABIVersion first.
+#
+if [ -z "$ABIVersion" ] ; then ABIVersion="1:1" ; fi
+# Extract the version numbers from the ABIVersion (needed in creating
+# the library names)
+majorVersion=`expr $ABIVersion : '\(.*\):.*'`
+minorVersion=`expr $ABIVersion : '.*:\(.*\)'`
+if [ -z "$majorVersion" ] ; then
+    echo "Invalid ABIVerion $ABIVersion - should be n:m"
+    exit 1
+fi
+if [ -z "$minorVersion" ] ; then
+    echo "Invalid ABIVerion $ABIVersion - should be n:m"
+    exit 1
+fi
+if [ "$minorVersion" = "0" ] ; then
+    echo "Minor version number must be greater than zero"
+    exit 1
+fi
+dottedVersion=`echo $ABIVersion | sed -e 's/:/./g'`
+#
+# Now we can create the names
+realName=
+soName=
+altNames=
+case $libtype in 
+    gcc-osx|osx-gcc)
+    soname=$srclibbase.$dottedVersion.$SHLIB_EXT
+    realName=$srclibbase.$dottedVersion.$SHLIB_EXT
+    altNames="$srclibbase.$SHLIB_EXT"
+    if [ -n "$majorVersion" ] ; then
+	altNames="$altNames $srclibbase.$majorVersion.$SHLIB_EXT"
+    fi
+    # Version numbers extracted above
+    minorVersionArg="-current_version $minorVersion"
+    ;;
+
+    *)
+    # Typical Unix default
+    soName=$srclibbase.$SHLIB_EXT.$dottedVersion
+    realName=$srclibbase.$SHLIB_EXT.$dottedVersion
+    altNames="$srclibbase.$SHLIB_EXT"
+    if [ -n "$majorVersion" ] ; then
+	altNames="$altNames $srclibbase.$SHLIB_EXT.$majorVersion"
+    fi
+    ;;
+esac
 
 # Now, process the steps
 
@@ -118,7 +222,7 @@ postmode=""
 if [ $mode = install ] ; then
     postmode=install
     case $libtype in 
-	gcc-osx)
+	gcc-osx|osx-gcc)
 	# Rebuild the library with a new install name.  We do this by 
 	# changing the mode to link and performing the install later.
 	mode=link
@@ -146,13 +250,18 @@ if [ $mode = link ] ; then
 
     case $libtype in 
 	gcc-osx|osx-gcc)
+	# Under OSX, the major version should be included in the library
+	# Name (as an extension before the .dylib) and the minor version with 
+        # the -current_version num 
+        # argument.  See http://developer.apple.com/documentation/DeveloperTools/Conceptual/DynamicLibraries/index.html 
+	# for more information
         # Mac OS/X
 	if [ -z "$destlibname" ] ; then
 	    abssrclibdir=`(cd $srclibdir && pwd)`
-	    destlibname="$abssrclibdir/$srclibbase.$SHLIB_EXT"
+	    destlibname="$abssrclibdir/$realName"
 	fi
-	$Show ${C_LINK_SHL} -o $srclibbase.$SHLIB_EXT \
-	    -install_name $destlibname .tmp/*.o
+	$Show ${C_LINK_SHL} -o $realName \
+	    $minorVersionArg -install_name $destlibname .tmp/*.o
 	;;		
 
 	cygwin|cygwin-gcc)
@@ -164,7 +273,7 @@ if [ $mode = link ] ; then
 	# will cause only those symbols to be exported.
 	# Note that we include any dependent libs because these are needed
 	# for Windows-style dlls
-	$Show ${C_LINK_SHL} -o $srclibbase.$SHLIB_EXT $exportDefs \
+	$Show ${C_LINK_SHL} -o $realName $exportDefs \
 	    -Wl,--out-implib,$srclibbase.a \
 	    .tmp/*.o $dependentLibs
 	# Create the import library
@@ -181,9 +290,20 @@ if [ $mode = link ] ; then
 
 	*)
         # This is the default model
-	$Show ${C_LINK_SHL} -o $srclibbase.$SHLIB_EXT .tmp/*.o
+        # Typically -Wl,-h,$soName
+	# FIXME: C_LINK_SHL knows the options for shared libraries,
+	# but not the args for setting the soname.
+	$Show ${C_LINK_SHL} -o $realName -Wl,-h,$soName .tmp/*.o 
+	# Do we need to add $dependentLibs ?
 	;;
     esac
+    if [ -n "$altNames" ] ; then
+        for alt in $altNames ; do
+	    # Remove any alternate names before executing the ln step
+	    rm -f $alt
+            $Show ln -s $realName $alt
+        done
+    fi
 
     # Common cleanup code
     rm -rf .tmp
@@ -198,14 +318,34 @@ else
 fi
 
 if [ "$postmode" = install ] ; then
-    if [ -z "$destlibname" ] ; then
-	destlibname="$destdir/$srclibname.$SHLIB_EXT"
+    # See if the destBaseName is included in the altnames.  If so,
+    # use the realName to form the destlibname instead
+    foundName=no
+    if [ -n "$altNames" -a -n "$destBaseName" ] ; then
+        for alt in $altNames ; do
+            if [ "$destBaseName" = "$alt" ] ; then
+	        foundName=yes
+	        break
+            fi
+        done
     fi
-    $Show $INSTALL_PROGRAM $srclibdir/$srclibbase.$SHLIB_EXT $destlibname
+    if [ -z "$destlibname" -o $foundName = yes ] ; then
+	destlibname="$destdir/$realName"
+    fi
+    if [ -z "$destdir" ] ; then
+	echo "The destination directory was not set."
+        exit 1
+    fi
+    $Show $INSTALL_PROGRAM $srclibdir/$realName $destlibname
     if [ "$libtype" = "cygwin-gcc" ] ; then
 	# We must also install the import library
 	# Eventually, we might want to install the .dll and the .a 
 	# into different directories
 	$Show $INSTALL_PROGRAM $srclibdir/$srclibbase.a $destdir/$srclibbase.a
+    fi
+    if [ -n "$altNames" ] ; then
+        for alt in $altNames ; do
+            ( cd $destdir && $Show rm -f $alt && $Show ln -s $realName $alt )
+        done
     fi
 fi
